name: join_my_ship
version: 1.2.0+64
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=2.17.0"

dependencies:
  get_cli: ^1.8.1
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter:
    sdk: flutter
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.7.0
  carousel_slider: ^4.2.1
  google_fonts: ^5.1.0
  collection: ^1.17.0
  firebase_auth: ^4.2.2
  firebase_core: ^2.10.0
  pinput: ^3.0.0
  fluttertoast: ^8.2.1
  dropdown_button2: ^2.1.0
  image_picker: ^1.0.2
  firebase_messaging: ^14.6.1
  get_it: ^7.6.0
  shared_preferences: ^2.1.1
  lottie: ^2.5.0
  cached_network_image: ^3.2.3
  country_picker: ^2.0.20
  curved_navigation_bar: ^1.0.3
  flutter_typeahead: ^4.6.2
  time_machine: ^0.9.17
  device_info_plus:
  flutter_document_picker: ^5.2.3
  text_form_field_validator: ^0.0.3
  url_launcher: ^6.1.12
  package_info_plus: ^4.1.0
  uni_links: ^0.5.1
  share_plus: ^7.1.0
  widgets_to_image: ^0.0.2
  path_provider: ^2.1.0
  connectivity_plus: ^4.0.2
  flutter_downloader: ^1.11.1
  story_view: ^0.15.0
  infinite_scroll_pagination: ^4.0.0
  flutter_secure_storage: ^9.0.0
  firebase_remote_config: ^4.3.8
  razorpay_flutter: ^1.3.6
  firebase_crashlytics: ^3.4.9
  intl: ^0.18.1
  dotted_border: ^2.1.0
  in_app_review: ^2.0.9

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/images/
    - assets/images/info/
    - assets/images/choose_user/
    - assets/images/crew_sign_in/
    - assets/images/email_verification/
    - assets/images/account_under_verification/
    - assets/images/dashboard/
    - assets/images/profile/
    - assets/images/employer_invite/
    - assets/images/job_post_under_verification/
    - assets/icons/
    - assets/animations/
