name: join_mp_ship
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.2 <3.0.0'

dependencies: 
  get_cli: ^1.8.1
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.7.0
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  collection: ^1.17.0
  firebase_auth: ^4.2.2
  firebase_core: ^2.10.0
  pinput: ^2.2.31
  fluttertoast: ^8.2.1

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/images/
  - assets/images/info/
  - assets/images/choose_user/
  - assets/images/crew_sign_in/

