name: join_mp_ship
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.12.0 <3.0.3'

dependencies: 
  get_cli: ^1.8.1
  cupertino_icons: ^1.0.2
  get: 4.6.5
  flutter: 
    sdk: flutter
  flutter_svg: ^2.0.5
  flutter_screenutil: ^5.7.0
  carousel_slider: ^4.2.1
  google_fonts: ^4.0.3
  collection: ^1.17.0
  firebase_auth: ^4.2.2
  firebase_core: ^2.10.0
  pinput: ^2.2.31
  fluttertoast: ^8.2.1
  dropdown_button2: ^2.1.0
  image_picker: ^0.8.7+4
  firebase_messaging: ^14.6.1
  file_picker: ^4.6.1
  get_it: ^7.6.0
  shared_preferences: ^2.1.1
  flutter_secure_storage: ^8.0.0
  lottie: 

dev_dependencies: 
  flutter_lints: ^2.0.0
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true
  assets:
  - assets/
  - assets/images/
  - assets/images/info/
  - assets/images/choose_user/
  - assets/images/crew_sign_in/
  - assets/images/email_verification/
  - assets/images/account_under_verification/

