part of 'app_pages.dart';
// DO NOT EDIT. This is code generated via package:get_cli/get_cli.dart

abstract class Routes {
  Routes._();
  static const HOME = _Paths.HOME;
  static const SPLASH = _Paths.SPLASH;
  static const INFO = _Paths.INFO;
  static const CHOOSE_USER = _Paths.CHOOSE_USER;
  static const CREW_SIGN_IN_EMAIL = _Paths.CREW_SIGN_IN_EMAIL;
  static const CREW_SIGN_IN_MOBILE = _Paths.CREW_SIGN_IN_MOBILE;
  static const SIGN_UP_EMAIL = _Paths.SIGN_UP_EMAIL;
  static const CHOOSE_EMPLOYER = _Paths.CHOOSE_EMPLOYER;
  static const SIGN_UP_PHONE_NUMBER = _Paths.SIGN_UP_PHONE_NUMBER;
  static const CREW_ONBOARDING = _Paths.CREW_ONBOARDING;
  static const EMAIL_VERIFICATION_WAITING = _Paths.EMAIL_VERIFICATION_WAITING;
  static const ACCOUNT_UNDER_VERIFICATION = _Paths.ACCOUNT_UNDER_VERIFICATION;
  static const PROFILE = _Paths.PROFILE;
  static const HELP = _Paths.HELP;
  static const EMPLOYER_CREATE_USER = _Paths.EMPLOYER_CREATE_USER;
  static const EMPLOYER_INVITE_NEW_MEMBERS = _Paths.EMPLOYER_INVITE_NEW_MEMBERS;
  static const EMPLOYER_MANAGE_USERS = _Paths.EMPLOYER_MANAGE_USERS;
  static const CHANGE_PASSWORD = _Paths.CHANGE_PASSWORD;
  static const RESET_PASSWORD = _Paths.RESET_PASSWORD;
  static const RESET_PASSWORD_EMAIL_VERIFICATION =
      _Paths.RESET_PASSWORD_EMAIL_VERIFICATION;
  static const JOB_POST = _Paths.JOB_POST;
  static const JOB_POSTED_SUCCESSFULLY = _Paths.JOB_POSTED_SUCCESSFULLY;
  static const VIEW_JOBS_POSTED = _Paths.VIEW_JOBS_POSTED;
  static const EMPLOYER_JOB_APPLICATIONS = _Paths.EMPLOYER_JOB_APPLICATIONS;
  static const EMPLOYER_JOB_POSTS = _Paths.EMPLOYER_JOB_POSTS;
  static const JOB_OPENINGS = _Paths.JOB_OPENINGS;
  static const JOB_APPLIED_SUCCESSFULLY = _Paths.JOB_APPLIED_SUCCESSFULLY;
  static const SUCCESS = _Paths.SUCCESS;
  static const CREW_JOB_APPLICATIONS = _Paths.CREW_JOB_APPLICATIONS;
  static const APPLICANT_DETAIL = _Paths.APPLICANT_DETAIL;
  static const APPLICATION_STATUS = _Paths.APPLICATION_STATUS;
  static const ERROR_OCCURRED = _Paths.ERROR_OCCURRED;
  static const JOB_OPENING = _Paths.JOB_OPENING;
  static const CONNECTIVITY_LOST = _Paths.CONNECTIVITY_LOST;
  static const COMPANIES = _Paths.COMPANIES;
  static const COMPANY_DETAIL = _Paths.COMPANY_DETAIL;
  static const FOLLOW = _Paths.FOLLOW;
  static const LIKED_JOBS = _Paths.LIKED_JOBS;
  static const CREW_LIST = _Paths.CREW_LIST;
  static const SUBSCRIPTIONS = _Paths.SUBSCRIPTIONS;
  static const BOOSTING = _Paths.BOOSTING;
  static const BOOSTED_JOBS = _Paths.BOOSTED_JOBS;
  static const BOOSTED_CREW_PROFILES = _Paths.BOOSTED_CREW_PROFILES;
  static const CREW_DETAIL = _Paths.CREW_DETAIL;
  static const CREW_REFERRAL = _Paths.CREW_REFERRAL;
  static const NOTIFICATION = _Paths.NOTIFICATION;
  static const JOB_POST_UNDER_VERIFICATION = _Paths.JOB_POST_UNDER_VERIFICATION;
  static const UPDATE_EMAIL = _Paths.UPDATE_EMAIL;
  static const WALLET = _Paths.WALLET;
  static const ADD_CREDITS = _Paths.ADD_CREDITS;
}

abstract class _Paths {
  _Paths._();
  static const HOME = '/home';
  static const SPLASH = '/splash';
  static const INFO = '/info';
  static const CHOOSE_USER = '/choose-user';
  static const CREW_SIGN_IN_EMAIL = '/crew-sign-in-email';
  static const CREW_SIGN_IN_MOBILE = '/crew-sign-in-mobile';
  static const SIGN_UP_EMAIL = '/sign-up-email';
  static const CHOOSE_EMPLOYER = '/choose-employer';
  static const SIGN_UP_PHONE_NUMBER = '/sign-up-phone-number';
  static const CREW_ONBOARDING = '/crew-onboarding';
  static const EMAIL_VERIFICATION_WAITING = '/email-verification-waiting';
  static const ACCOUNT_UNDER_VERIFICATION = '/account-under-verification';
  static const PROFILE = '/profile';
  static const HELP = '/help';
  static const EMPLOYER_CREATE_USER = '/employer-create-user';
  static const EMPLOYER_INVITE_NEW_MEMBERS = '/employer-invite-new-members';
  static const EMPLOYER_MANAGE_USERS = '/employer-manage-users';
  static const CHANGE_PASSWORD = '/change-password';
  static const RESET_PASSWORD = '/reset-password';
  static const RESET_PASSWORD_EMAIL_VERIFICATION =
      '/reset-password-email-verification';
  static const JOB_POST = '/job-post';
  static const JOB_POSTED_SUCCESSFULLY = '/job-posted-successfully';
  static const VIEW_JOBS_POSTED = '/view-jobs-posted';
  static const EMPLOYER_JOB_APPLICATIONS = '/employer-job-applications';
  static const EMPLOYER_JOB_POSTS = '/employer-job-posts';
  static const JOB_OPENINGS = '/job-openings';
  static const JOB_APPLIED_SUCCESSFULLY = '/job-applied-successfully';
  static const SUCCESS = '/success';
  static const CREW_JOB_APPLICATIONS = '/crew-job-applications';
  static const APPLICANT_DETAIL = '/applicant-detail';
  static const APPLICATION_STATUS = '/application-status';
  static const ERROR_OCCURRED = '/error-occurred';
  static const JOB_OPENING = '/job-opening';
  static const CONNECTIVITY_LOST = '/connectivity-lost';
  static const COMPANIES = '/companies';
  static const COMPANY_DETAIL = '/company-detail';
  static const FOLLOW = '/follow';
  static const LIKED_JOBS = '/liked-jobs';
  static const CREW_LIST = '/crew-list';
  static const SUBSCRIPTIONS = '/subscriptions';
  static const BOOSTING = '/boosting';
  static const BOOSTED_JOBS = '/boosted-jobs';
  static const BOOSTED_CREW_PROFILES = '/boosted-crew-profiles';
  static const CREW_DETAIL = '/crew-detail';
  static const CREW_REFERRAL = '/crew-referral';
  static const NOTIFICATION = '/notification';
  static const JOB_POST_UNDER_VERIFICATION = '/job-post-under-verification';
  static const UPDATE_EMAIL = '/update-email';
  static const WALLET = '/wallet';
  static const ADD_CREDITS = '/add-credits';
}
